import path from 'node:path';
import { createRequire } from 'node:module';
const { chromium } = createRequire(path.join(process.cwd(), 'package.json'))('playwright');
import fs from 'node:fs';
const b = await chromium.launch({ args: ['--use-gl=angle', '--use-angle=swiftshader', '--enable-unsafe-swiftshader'] });
const p = await b.newPage({ viewport: { width: 1440, height: 900 }, deviceScaleFactor: 2, reducedMotion: 'reduce' });
await p.goto('http://localhost:3100', { waitUntil: 'networkidle' });
await p.evaluate(() => document.getElementById('predictor').scrollIntoView());
await p.waitForTimeout(1500);
const panel = p.locator('#predictor .panel').first();
await p.getByRole('button', { name: /#6/ }).click();
await p.mouse.move(0, 0);
await p.waitForTimeout(800);
await panel.screenshot({ path: 'assets/cap/predictor_pre.png' });
const pb = await panel.boundingBox();
const bb = await p.getByRole('button', { name: /Run ML inference/ }).boundingBox();
await p.getByRole('button', { name: /Run ML inference/ }).click();
await p.mouse.move(0, 0);
await p.waitForTimeout(2000);
await panel.screenshot({ path: 'assets/cap/predictor_post.png' });
const pb2 = await panel.boundingBox();
fs.writeFileSync('assets/cap/predictor.json', JSON.stringify({ panel: pb, panelPost: pb2, button: { x: bb.x - pb.x, y: bb.y - pb.y, w: bb.width, h: bb.height } }, null, 1));
console.log(fs.readFileSync('assets/cap/predictor.json', 'utf8'));
await b.close();
